packages:
  - "apps/*"

allowBuilds:
  cpu-features: false
  esbuild: true
  msgpackr-extract: false
  protobufjs: false
  ssh2: false
  unrs-resolver: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - "@nestjs/*"
  - "nestjs"
